### PR TITLE
Exposing variables

### PR DESCRIPTION
**Pull request by Jasperav**
This makes some variables `pub` so I can send the bytes from a paging function to clients which they can send back to retrieve the next page.

Note: I did not expose the `bytes` variable but created a method `into_bytes` so the CBytes can never be created by a user. I don't like the `get_cursor` method on `PagerState` because that uses a `clone` which is unnecessary (in my case).

### CODE REVIEW

**Comment by krojew** [comment]
I think a getter/into_* approach is better than making things public - why not a function which will transform the state into bytes? Also, the change should be reflected in `ExecPager`.

**Comment by Jasperav** [comment]
I don't think it is an idiomatic way to create getters functions for variables, this isn't Java. The `pub` keyword for variables give callers the choice to either take ownership of the variable (the into function) or take it as a ref (the getter function). Creating those functions ourself and hiding the variable by not marking it as `pub`, are in my eyes just verbose functions. 

But I will create those functions for this PR

**Comment by krojew** [comment]
I was rather thinking about an `info_*` function. Notice that you're effectively transforming `PagerState` into bytes. This can be achieved by an `into_bytes` function or similar, without making internals `pub`.

**Comment by Jasperav** [comment]
I think you mean `into` :) yes I made the `into` changes with the latest commit

**Pull request merged**
