### PR TITLE
ResponseBody into error method

### PR DESCRIPTION
**Pull request by conorbros**
Adding this because I needed it and we have methods for all the other result types so makes sense having one for error too.

### CODE REVIEW

**Comment by krojew** [comment]
If you have other additions you'd like to see, it would be great to add them before the next release.

**Comment by conorbros** [comment]
When are you planning the release? (Bringing 7.0.0 out of beta I mean)

**Comment by krojew** [comment]
> When are you planning the release? (Bringing 7.0.0 out of beta I mean)

Not sure yet. For now, everything seems to be working fine, but I would like to give people about a month to test everything out.

**Comment by conorbros** [comment]
Sounds good, I'm in the process of adding cdrs-tokio to our test suite alongside the Datastax cpp. Have found a couple things that need fixings, I'll submit a PR by tomorrow.

**Pull request merged**
