### PR TITLE
add rustfmt and rust-toolchain files

### PR DESCRIPTION
**Pull request by conorbros**
Makes the project play nice with IDEs.

### CODE REVIEW

**Comment by krojew** [comment]
Doesn't this force users to use that particular rust version?

**Comment by conorbros** [comment]
Hmm true, should I remove the toolchain file?

**Comment by krojew** [comment]
We shouldn't force a concrete version if there's no need to.

**Comment by krojew** [comment]
One more thing - we're using the 2018 edition, while rustfmt.toml uses 2021.

**Pull request merged**
