### PR TITLE
query params decoding

### PR DESCRIPTION
**Pull request by rukai**
* I had to add `test_encode_decode_roundtrip_nondeterministic` because of the hashmap in NamedValues

### CODE REVIEW

**Comment by krojew** [comment]
According to the protocol spec, we can't get QUERY inside a response. What's the motivation behind this change?

**Comment by rukai** [comment]
The motivation is to allow decoding of query params for use in a proxy or cassandra reimplementation.
Later on I was planning on renaming ResponseBody to something more general as it holds both responses and requests.
Tomorrow I'll investigate and figure out the way best way to represent responses + requests given that we now want to be able to decode/encode both of them.

**Comment by krojew** [comment]
I think you definitely need to add something new, which will contain both. `ResponseBody` was obviously intended to hold only responses and I have no idea why somebody also added requests there.

**Comment by rukai** [comment]
ResponseBody's only purpose is being the type that is returned from Frame::body to contain the body of the frame.
In that sense I dont see a problem with it being repurposed and renamed to hold any potential body of the frame including both requests and responses.

An alternative approach would be to replace `Frame::body() -> ResponseBody` with `Frame::response_body() -> ResponseBody` and `Frame::request_body() -> RequestBody`.
I think this approach will work fine for our purposes and is nicer for cassandra clients than the first approach.
So I'll go ahead with this second approach.

**Comment by rukai** [comment]
Ready for review again.
Splitting ResponseBody -> ResponseBody + RequestBody made this PR quite large so let me know if you want me to pull that out into a prereq PR.

**Pull request merged**
