### PR TITLE
Make invalid states unrepresentable in ErrorBody

### PR DESCRIPTION
**Pull request by rukai**
error_code can just be derived from the AdditionalErrorInfo at encode time.

### CODE REVIEW

**Comment by krojew** [comment]
I see two problems with this change:

1. Current structure corresponds to the error specification as defined in the protocol (section 8). Cassandra decouples error codes from additional info, so we might run into problems if we glue them together.
2. This is a breaking change, so it needs to be done in a backwards-compatible manner.

**Comment by rukai** [comment]
1. Maybe I'm misinterpreting the spec but error codes and additional info seem extremely tightly coupled to me.
   https://github.com/apache/cassandra/blob/73c0f7f2af061e8b7e79566e986769a06b06412a/doc/native_protocol_v5.spec#L1259
   Each error code is defined with its own unique additional info specification. For most error codes this is the complete lack of additional info, but for some they have their own unique additional info defined that is only compatible with that error code.
2. This change is inherently breaking, I cant think of a way to avoid that. I'm happy for this PR to wait around until you start thinking about an 8.0.0 release if thats what you want to do.

**Comment by krojew** [comment]
Can you rebase it on the 8.0-dev branch?

**Comment by rukai** [comment]
I rebased on 8.0-dev branch and changed the base of the PR in the github UI.

**Comment by rukai** [comment]
The CI failure also occurs on master

**Comment by rukai** [comment]
Oh, looks like you've already fixed it.
I've rebased again.

**Comment by krojew** [comment]
Yes, new Rust version added more clippy checks. Should be fixed now.

**Comment by krojew** [comment]
Can you also add `#[non_exhaustive]` to `ErrorType`?

**Comment by rukai** [comment]
done

**Pull request merged**
