### PR TITLE
Added more paging assertions

### PR DESCRIPTION
**Pull request by Jasperav**
I want to make sure this functionality works correctly, so I added more assertions

### CODE REVIEW

**Comment by krojew** [comment]
Sure, but those would make more sense in tests.

**Comment by Jasperav** [comment]
These are the test, or do you mean something else?

**Comment by krojew** [comment]
You modified an example. Tests are here: https://github.com/krojew/cdrs-tokio/tree/master/tests

**Comment by Jasperav** [comment]
Ah my bad, I didn't see that. I will convert it into a test!

**Comment by krojew** [comment]
e2e are end-to-end tests, which were a bit funky since the old cdrs days.

**Comment by krojew** [comment]
Can you rebase this PR? We'll see if it passes.

**Comment by Jasperav** [comment]
@krojew Not sure why github shows '33 files changed' for this PR. I will create a new PR, not sure what went wrong with this one

**Pull request closed without merging**
